version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 30
  versioning-strategy: increase
  groups:
    webpack-cli:
      applies-to: version-updates
      patterns:
      - "webpack-cli"
      - "@webpack-cli/*"
    jest:
      applies-to: version-updates
      patterns:
      - "jest"
      - "@types/jest"
      - "ts-jest"
      - "jest-environment-jsdom"
