version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: ts-loader
    versions:
    - 8.0.17
    - 8.0.18
    - 9.0.0
    - 9.1.0
  - dependency-name: hls.js
    versions:
    - 1.0.1
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.4.0
    - 1.5.0
  - dependency-name: webpack
    versions:
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.1
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.32.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
  - dependency-name: css-loader
    versions:
    - 5.1.1
    - 5.1.2
    - 5.1.3
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: ts-jest
    versions:
    - 26.5.2
    - 26.5.3
  - dependency-name: plyr
    versions:
    - 3.6.4
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.9.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
  - dependency-name: "@webpack-cli/serve"
    versions:
    - 1.2.2
  - dependency-name: boclips-js-security
    versions:
    - 5.0.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
