---
jobs:
- name: test
  plan:
  - get: once-per-weekday
    trigger: true
  - get: source
    trigger: true
  - task: test
    file: source/pipeline/test.yml

- name: major
  plan:
  - put: version
    params:
      bump: major
      pre: dev

- name: minor
  plan:
  - put: version
    params:
      bump: minor
      pre: dev

- name: patch
  plan:
  - put: version
    params:
      bump: patch
      pre: dev

- name: release
  plan:
  - get: source
    passed: [test]
  - get: version
    params:
      bump: final
  - task: release
    file: source/pipeline/release.yml
  - put: npm-registry
    params:
      username: ((npm-username))
      password: ((npm-password))
      email: engineering@boclips.com
      path: dist
  - put: github-release
    params:
      name: release/name
      tag: release/name
      body: release/notes
      commitish: source/.git/ref
  - put: version
    params:
      file: version/version

resources:
- name: source
  type: git
  source:
    branch: master
    private_key: ((boclips-player-repo-key))
    uri: git@github.com:boclips/boclips-player.git

- name: version
  type: semver
  source:
    initial_version: "0.1.0"
    driver: git
    uri: git@github.com:boclips/versions.git
    branch: master
    file: boclips-player
    private_key: ((versions-repo-key))

- name: npm-registry
  type: npm-resource
  source:
    package_name: boclips-player

- name: once-per-weekday
  type: time
  source:
    start: 09:30 AM
    stop: 12:30 PM
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    location: Europe/London

- name: github-release
  type: github-release
  source:
    owner: boclips
    repository: boclips-player
    access_token: ((github-access-token))

resource_types:
- name: npm-resource
  type: docker-image
  source:
    repository: idahobean/npm-resource
