import {
  ApiOptions,
  defaultApiOptions,
} from '../BoclipsApiClient/BoclipsApiClient';
import {
  AnalyticsOptions,
  defaultAnalyticsOptions,
} from '../Events/AnalyticsOptions';
import {
  defaultInterfaceOptions,
  InterfaceOptions,
} from '../MediaPlayer/InterfaceOptions';
import { PlaybackSegment } from '../MediaPlayer/MediaPlayer';

export interface PlayerOptions {
  analytics: AnalyticsOptions;
  api: ApiOptions;
  debug: boolean;
  interface: InterfaceOptions;
  displayAutogeneratedCaptions?: boolean;
  segment?: PlaybackSegment;
}

export interface AddonOptions {
  interface: InterfaceOptions;
  segment?: PlaybackSegment;
}

export const defaultOptions: PlayerOptions = Object.freeze({
  analytics: defaultAnalyticsOptions,
  api: defaultApiOptions,
  debug: false,
  interface: defaultInterfaceOptions,
});
