= Boclips Player
Boclips Engineering;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[boclips-player]]
== Overview

Boclips Player is a framework agnostic video player which serves to play
Boclips supplied videos on all our supported devices. It will feature
core functionality that is expected of modern video players, such as
analytics, closed captions, and adaptive bit rate streaming.

It will be integrated into other apps used by our API partners. We want
to provide these partners with a complete player solution that allows us
to gain insights to how our consumers watch our videos.

[[usage]]
== Usage

In order to render the Boclips Player on your page you should load the
Javascript and CSS assets in the `head` section.

Boclips Player is hosted in the unpkg.com CDN

In order to load a video you must have a Video URI pointing to our API.

[NOTE]
====
Our API is protected by several methods, one of these is CORs. Since the `boclips-player`
makes API requests to our server you'll need to ensure we've whitelisted any domains where
you load our player.

In order to do this, please get in touch with us with a list of domain names (including
protocols and any port numbers -- if required) that will host this player.
====

=== Loaded via a script tag

When this library is loaded via a script tag on a web page it exposes the `PlayerFactory` under the global variable `Boclips`. See <<module-import>> for more information on the interface.

==== Programmatically

You can instantiate a Player by providing a HTML container, this will encapsulate the video player. The `Player` API allows you to load videos programmatically.

You must pass a video URI endpoint to `Player.loadVideo`. See link:https://docs.boclips.com/docs/api-guide.html#resources-video-access[Video Access] for more information.

[source,html]
----
<html>
<head>
    <title>Plain Demo</title>
    <script src="https://unpkg.com/boclips-player/dist/boclips-player.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://unpkg.com/boclips-player/dist/boclips-player.css" type="text/css"/>
</head>
<body>
<div id="container"></div>
<script type="text/javascript">
    const container = document.querySelector('#container');
    const player = Boclips.PlayerFactory.get(container);
    player.loadVideo('https://path.to.our/video/endpoint/1');
</script>
</body>
</html>
----

==== Data Driven

You may also instantiate multiple players on a single page using the `data-boclips-player-container` attribute on the container elements.

You must add a `data-boplayer-video-uri` attribute to point to the video URI endpoint. See link:https://docs.boclips.com/docs/api-guide.html#resources-video-access[Video Access] for more information.

[source,html]
----
<html>
<head>
    <title>Plain Demo</title>
    <script src="https://unpkg.com/boclips-player/dist/boclips-player.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://unpkg.com/boclips-player/dist/boclips-player.css" type="text/css"/>
</head>
<body>
    <div data-boclips-player-container data-boplayer-video-uri="https://path.to.our/video/endpoint/1"></div>
    <div data-boclips-player-container data-boplayer-video-uri="https://path.to.our/video/endpoint/2"></div>
    <script>
      Boclips.PlayerFactory.scan();
    </script>
</body>
</html>
----

[[module-import]]
=== Importing as a module

You can use the boclips-player as a module in your JavaScript application.

[source,typescript]
----
interface PlayerFactory {
    get: (
        container: HTMLElement | string,
        options: PlayerOptions = {}
    ) => Player;
    getSeveral = (
        containers: Array<HTMLElement | string> | string,
    ): Player[];
    scan = (): Player[];
}

interface PlayerOptions {
    analytics: Partial<AnalyticsOptions>;
    player: Partial<WrapperOptions>;
}

interface WrapperOptions {
    controls: Controls[];
}

interface AnalyticsOptions {
    metadata: { [key: string]: any };
    handleOnPlayback: (event: PlaybackEvent) => void;
}

interface Player {
    play: () => Promise<void>;
    pause: () => void;
    loadVideo: (videoUri: string) => void;
}
----

[[analytics]]
== Analytics

In order to gain insights into the way in which our users watch our curated videos we provide some analytics out of the
box. We use this data internally to make decisions on acquisition, and promotion of videos.

We do this by triggering events when certain user actions occur. Detailed information on these tracking mechanisms may
be gleaned by inspecting the source code of this project.

Where appropriate we ask that you enrich these events with extra data. See <<analytics-metadata>>

This information will strictly be processed in accordance with our https://www.boclips.com/privacy-policy[Privacy Policy].

[[analytics-metadata]]
=== Additional Metadata

To gain the best insights we ask that you provide extra data about the circumstance that this player is being used.

When initialising the player, you may pass metadata into the analytics module. For example, the position the video came
in search results:

[source,typescript]
----
const options = {
    analytics: {
        metadata: {
            videoIndex: results.indexOf(video)
        }
    }
}

const player = Boclips.PlayerFactory.get(document.querySelector('#player-container'), options);
player.loadVideo(video);
----



[[license]]
== License

BSD 3-Clause "New" or "Revised" License

Copyright (c) 2019, Knowledgemotion Ltd All rights reserved.