= Boclips Player
Boclips Engineering;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[boclips-player]]
== Overview

Boclips Player is a framework agnostic HTML5 video player which serves to play
Boclips supplied videos on all our supported devices. It will feature
core functionality that is expected of modern video players, such as
analytics, closed captions, and adaptive bit rate streaming.

It can be integrated into JavaScript applications with ease. We are fully committed
to provide partners with a complete player solution that allows us
to gain insights to how our consumers watch our videos.

[[usage]]
== Usage

In order to render the Boclips Player on your page you should load the
Javascript and CSS assets in the `head` section.

Boclips Player is hosted in the unpkg.com CDN

In order to load a video you must have a Video URI pointing to our API.

[NOTE]
====
Our API is protected by several methods, one of these is CORS. Since the `boclips-player`
makes API requests to our server you'll need to ensure we've whitelisted any domains where
you load our player.

In order to do this, please get in touch with us with a list of domain names (including
protocols and any port numbers -- if required) that will host this player.
====

=== Loaded via a script tag

When this library is loaded via a script tag on a web page it exposes the `PlayerFactory` under the global variable `Boclips`. See <<module-import>> for more information on the interface.

==== Programmatically

You can instantiate a Player by providing a HTML container, this will encapsulate the video player. The `Player` API allows you to load videos programmatically.

You must pass a video URI endpoint to `Player.loadVideo`. See link:https://docs.boclips.com/docs/api-guide.html#resources-video-access[Video Access] for more information.

[source,html]
----
<html>
<head>
    <title>Plain Demo</title>
    <script src="https://unpkg.com/boclips-player/dist/boclips-player.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://unpkg.com/boclips-player/dist/boclips-player.css" type="text/css"/>
</head>
<body>
<div id="container"></div>
<script type="text/javascript">
    const container = document.querySelector('#container');
    const player = Boclips.PlayerFactory.get(container);
    player.loadVideo('https://path.to.our/video/endpoint/1');
</script>
</body>
</html>
----

==== Data Driven

You may also instantiate multiple players on a single page using the `data-boclips-player-container` attribute on the container elements.

You must add a `data-boplayer-video-uri` attribute to point to the video URI endpoint. See link:https://docs.boclips.com/docs/api-guide.html#resources-video-access[Video Access] for more information.

[source,html]
----
<html>
<head>
    <title>Plain Demo</title>
    <script src="https://unpkg.com/boclips-player/dist/boclips-player.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://unpkg.com/boclips-player/dist/boclips-player.css" type="text/css"/>
</head>
<body>
    <div data-boclips-player-container data-boplayer-video-uri="https://path.to.our/video/endpoint/1"></div>
    <div data-boclips-player-container data-boplayer-video-uri="https://path.to.our/video/endpoint/2"></div>
    <script>
      Boclips.PlayerFactory.scan();
    </script>
</body>
</html>
----

[[module-import]]
=== Importing as a module

You can use the boclips-player as a module in your JavaScript application.

[source,typescript]
----
interface PlayerFactory {
    get: (
        container: HTMLElement | string,
        options: Partial<PlayerOptions> = {}
    ) => Player;
    getSeveral: (
        containers: Array<HTMLElement | string> | string,
    ) => Player[];
    scan: () => Player[];
}

interface Player {
    play: () => Promise<void>;
    pause: () => void;
    loadVideo: (videoUri: string, segment?: PlaybackSegment) => Promise<void>;
    destroy: () => void;
    getPlayerId: () => string;
    getOptions: () => Partial<PlayerOptions>;
}

interface PlayerOptions {
    analytics: Partial<AnalyticsOptions>;
    api: Partial<ApiOptions>;
    debug: boolean;
    interface: Partial<InterfaceOptions>;
}
----

=== Player Options

The various modules within the player accept optional parameters to drive the behaviour of the player.

==== Interface Options

[source,typescript]
----
interface InterfaceOptions {
    controls: Controls[];
    addons: {
        seekPreview?: boolean | SeekPreviewOptions;
        hoverPreview?: boolean | HoverPreviewOptions;
    };
}

type Controls =
  | 'play-large'
  | 'restart'
  | 'rewind'
  | 'play'
  | 'fast-forward'
  | 'progress'
  | 'current-time'
  | 'duration'
  | 'mute'
  | 'volume'
  | 'captions'
  | 'settings'
  | 'pip'
  | 'airplay'
  | 'download'
  | 'fullscreen';

interface SeekPreviewOptions {
    frameCount: number;
}

interface HoverPreviewOptions {
    frameCount: number;
    delayMilliseconds: number;
}
----

==== Boclips API Options

[source,typescript]
----
interface ApiOptions {
    /**
     * This callback should return a Promise which resolves a string to be used as the users authentication token.
     * For more information on generating a token see https://docs.boclips.com/docs/api-guide.html#overview-authentication
     *
     * If this callback rejects the promise for whatever reason, an error will be displayed to the user.
     */
    tokenFactory?: () => Promise<string>;
}
----

==== Analytics Options

[source,typescript]
----
interface AnalyticsOptions {
    metadata: { [key: string]: any };
    handleOnSegmentPlayback: (video: Video, startSeconds: number, endSeconds: number) => void;
}
----

[[authentication]]
== Authentication

The Boclips API requires authentication in order to accurately track viewer attribution and user engagement.

The Player allows the users token to be passed in as a `Promise<string>` in order to generate a valid token
for the user at the time that the player calls to the API. This is important as tokens do expire, it is your
responsibility to ensure that the token that is returned by `options.api.tokenFactory` is a valid token --
failure to do so may result in a poor experience for the user.

An example tokenFactory, using `boclips-js-security@2.0.1`:
```typescript
import { authenticate } from 'boclips-js-security';
import { isAuthenticated } from 'boclips-js-security/dist/src/authenticate';
import getGlobalKeycloak from 'boclips-js-security/dist/src/helpers/getGlobalKeycloak';

authenticate({
  onLogin: () => {
    console.log('Successfully authenticated');
    renderPlayer();
  },
  realm: 'boclips',
  clientId: 'teachers',
  mode: 'login-required',
  authEndpoint: 'https://login.staging-boclips.com/auth',
});

function tokenFactory() {
  return new Promise<string>(resolve => {
    return getGlobalKeycloak()
      .updateToken(5)
      .success(() => {
        if (isAuthenticated()) {
          resolve(getGlobalKeycloak().token);
        } else {
          throw new Error('Oh no - not authenticated!');
        }
      })
      .error(() => {
        throw new Error('Fatal authentication error occurred.');
      });
  });

function renderPlayer() {
  const player = PlayerFactory.get(playerContainer, {
    api: { tokenFactory },
  });
};
```

[WARNING]
====
`options.api.tokenFactory` is currently optional, however in a future release it will become mandatory.
====


[[analytics]]
== Analytics

In order to gain insights into the way in which our users watch our curated videos, the player reports basic view stats back to our backend systems. This information helps us to personalise the Boclips experience in the long-term.

Detailed information on these tracking mechanisms may be gleaned by inspecting the source code of this project.

Where appropriate we will ask you to enrich these events with extra data. See <<analytics-metadata>>

Any information provided will strictly be processed in accordance with our https://www.boclips.com/privacy-policy[Privacy Policy].

[[analytics-metadata]]
=== Additional Metadata

To gain the best insights we ask that you provide extra data about the circumstance that this player is being used.

When initialising the player, you may pass metadata into the analytics module. For example, what user is watching the video:

[source,typescript]
----
const options = {
    analytics: {
        metadata: {
            userId: user.id
        }
    }
}

const player = Boclips.PlayerFactory.get(document.querySelector('#player-container'), options);
player.loadVideo(video);
----

All analytics data should be anonymised.

[[license]]
== License

BSD 3-Clause "New" or "Revised" License

Copyright (c) 2019, Knowledgemotion Ltd All rights reserved.
