= Boclips Player
Boclips Engineering;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[boclips-player]]
= Overview

Boclips Player is a framework agnostic video player which serves to play
Boclips supplied videos on all our supported devices. It will feature
core functionality that is expected of modern video players, such as
analytics, closed captions, and adaptive bit rate streaming.

It will be integrated into other apps used by our API partners. We want
to provide these partners with a complete player solution that allows us
to gain insights to how our consumers watch our videos.

[[usage]]
== Usage

In order to render the Boclips Player on your page you should load the
Javascript and CSS assets in the `head` section.

Boclips Player is hosted in the unpkg.com CDN

In order to load a video you must have a Video URI pointing to our API.

=== Cross-Origin Resource Sharing

Our API is protected by several methods, one of these is CORs. Since the `boclips-player`
makes API requests to our server you'll need to ensure we've whitelisted any domains where
you load our player.

In order to do this, please get in touch with us with a list of domain names (including
protocols and any port numbers -- if required) that will host this player.

=== Programmatically

[source,html]
----
<html>
<head>
    <title>Plain Demo</title>
    <script src="https://unpkg.com/boclips-player/dist/boclips-player.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://unpkg.com/boclips-player/dist/boclips-player.css" type="text/css"/>
</head>
<body>
<div id="container"></div>
<script type="text/javascript">
    const container = document.querySelector('#container');
    const player = BoclipsPlayerFactory.get(container);
    player.loadVideo('https://path.to.our/video/endpoint/1');
</script>
</body>
</html>
----

=== Declaratively

[source,html]
----
<html>
<head>
    <title>Plain Demo</title>
    <script src="https://unpkg.com/boclips-player/dist/boclips-player.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://unpkg.com/boclips-player/dist/boclips-player.css" type="text/css"/>
</head>
<body>
    <div data-boclips-player-container data-boplayer-video-uri="https://path.to.our/video/endpoint/1"></div>
    <div data-boclips-player-container data-boplayer-video-uri="https://path.to.our/video/endpoint/2"></div>
    <script>
      BoclipsPlayerFactory.scan();
    </script>
</body>
</html>
----

[[javascript-api]]
=== JavaScript API

[[browser]]
==== In the Browser

When this library is loaded via a script tag on a web page it places a
factory method on the window.

[source,typescript]
----
interface BoclipsPlayerFactory {
    get: (
        container: HTMLElement | string,
        options: BoclipsPlayerOptions = {}
    ) => BoclipsPlayer;
    getSeveral = (
        containers: Array<HTMLElement | string> | string,
    ): BoclipsPlayer[];
    scan = (): BoclipsPlayer[];
}

interface BoclipsPlayerOptions {
    // There are currently no supported options.
}

interface BoclipsPlayer {
    play: () => Promise<void>;
    pause: () => void;
    loadVideo: (videoUri: string) => void;
}
----

[[license]]
== License

_TBC_